#!/bin/sh

#java -Xmx2G -jar Rootbeer.jar -runtest HamaTest
#java -Xmx2G -jar Rootbeer.jar -runtest HamaTest &> HamaTest.log
java -Xmx2G -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 -jar Rootbeer.jar -runtest HamaTest
