#!/bin/sh

java -Xmx2G -jar Rootbeer.jar -runtest HamaTest -nodoubles -norecursion \
     -loadclass edu.syr.pcpratts.rootbeer.testcases.rootbeertest.serialization.hama.TestGpuBSP

# Logging
#java -Xmx2G -jar Rootbeer.jar -runtest HamaTest &> HamaTest.log

# Debugging
#java -Xmx2G -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 -jar Rootbeer.jar -runtest HamaTest
