#!/bin/sh

java -Xmx2G -jar Rootbeer.jar -runtest HadoopTest -nodoubles -norecursion \
     -loadclass edu.syr.pcpratts.rootbeer.testcases.rootbeertest.serialization.hadoop.TestGpuMapper \
     -loadclass edu.syr.pcpratts.rootbeer.testcases.rootbeertest.serialization.hadoop.TestGpuReducer

# Logging
#java -Xmx2G -jar Rootbeer.jar -runtest HadoopTest &> HadoopTest.log

# Debugging
#java -Xmx2G -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 -jar Rootbeer.jar -runtest HadoopTest
