#!/bin/sh

java -Xmx2G -jar Rootbeer.jar -runtest SimpleTest
#java -Xmx2G -jar Rootbeer.jar -runtest SimpleTest &> SimpleTest.log
#java -Xmx2G -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 -jar Rootbeer.jar -runtest SimpleTest
