/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trifort_rootbeer_runtime_HamaPeer */

#ifndef _Included_org_trifort_rootbeer_runtime_HamaPeer
#define _Included_org_trifort_rootbeer_runtime_HamaPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trifort_rootbeer_runtime_HamaPeer
 * Method:    connect
 * Signature: (IZ)J
 */
JNIEXPORT jlong JNICALL Java_org_trifort_rootbeer_runtime_HamaPeer_connect
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
