/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles */

#ifndef _Included_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
#define _Included_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
 * Method:    doWriteLong
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles_doWriteLong
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles
 * Method:    doReadLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_edu_syr_pcpratts_rootbeer_runtime2_cuda_Handles_doReadLong
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
