#!/bin/sh

gcc -m32 -fPIC -g -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda/include org/trifort/rootbeer/runtime/FixedMemory.c -o FixedMemory.o
gcc -m32 -shared -Wl,-soname,rootbeer -o rootbeer_x86.so.1 FixedMemory.o -lc

g++ -m32 -fPIC -g -c at/illecker/HadoopUtils.cpp -o HadoopUtils.o
g++ -m32 -fPIC -g -c at/illecker/HostDeviceInterface.cpp -o HostDeviceInterface.o
g++ -m32 -fPIC -g -c at/illecker/SocketClient.cpp -o SocketClient.o
g++ -m32 -fPIC -g -c at/illecker/HostMonitor.cpp -o HostMonitor.o

gcc -m32 -fPIC -g -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda/include org/trifort/rootbeer/runtime/CUDARuntime.c -o CUDARuntime.o
g++ -m32 -fPIC -g -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda/include org/trifort/rootbeer/runtime/CUDAContext.c -o CUDAContext.o
g++ -m32 -shared -Wl,-soname,rootbeer_cuda -L /usr/local/cuda/lib/ -o rootbeer_cuda_x86.so.1 HadoopUtils.o SocketClient.o HostDeviceInterface.o HostMonitor.o CUDARuntime.o CUDAContext.o -lc -lcuda

gcc -m32 -fPIC -g -c -I/usr/lib/jvm/default-java/include/ -I/usr/lib/jvm/default-java/include/linux -I/usr/local/cuda/include org/trifort/rootbeer/runtime/OpenCLRuntime.c -o OpenCLRuntime.o
gcc -m32 -shared -Wl,-soname,rootbeer_opencl -o rootbeer_opencl_x86.so.1 OpenCLRuntime.o -lc -lOpenCL

